{
 "title": "kafka metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Valid messages consumed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(kafka_consumer_valid_messages_total[1m])) / sum(rate(kafka_producer_valid_messages_total[1m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalid messages consumed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(kafka_consumer_invalid_messages_total[1m])) / sum(rate(kafka_producer_invalid_messages_total[1m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer valid and invalid messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kafka_consumer_valid_messages_total",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "kafka_consumer_invalid_messages_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer valid and invalid messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "kafka_producer_valid_messages_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "kafka_producer_invalid_messages_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}