apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  replicas: ${PRODUCER_REPLICAS}
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: producer-consumer:latest
          imagePullPolicy: Never
          command: ["producer"] # Override the CMD to run producer
          env:
            - name: KAFKA_BROKER_NAME
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_BROKER_NAME
            - name: KAFKA_BROKER_PORT
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_BROKER_PORT
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_TOPIC
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  replicas: ${CONSUMER_REPLICAS}
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: producer-consumer:latest
          imagePullPolicy: Never
          command: ["consumer"] # Override the CMD to run consumer
          env:
            - name: KAFKA_BROKER_NAME
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_BROKER_NAME
            - name: KAFKA_BROKER_PORT
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_BROKER_PORT
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_TOPIC
            - name: KAFKA_DLQ_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_DLQ_TOPIC
