apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  replicas: ${PRODUCER_REPLICAS}
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: producer-consumer:latest
          imagePullPolicy: Never
          command: ["python", "producer.py"] # Override the CMD to run producer
          env:
            - name: KAFKA_BROKER_HOST
              value: "${KAFKA_BROKER_SERVICE_NAME}"
            - name: KAFKA_BROKER_PORT
              value: "${KAFKA_BROKER_PORT}"
            - name: KAFKA_TOPIC
              value: "${KAFKA_TOPIC}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  replicas: ${CONSUMER_REPLICAS}
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: producer-consumer:latest
          imagePullPolicy: Never
          command: ["python", "consumer.py"] # Override the CMD to run consumer
          env:
            - name: KAFKA_BROKER_HOST
              value: "${KAFKA_BROKER_SERVICE_NAME}"
            - name: KAFKA_BROKER_PORT
              value: "${KAFKA_BROKER_PORT}"
            - name: KAFKA_TOPIC
              value: "${KAFKA_TOPIC}"
            - name: KAFKA_DLQ_TOPIC
              value: "${KAFKA_DLQ_TOPIC}"
